#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10


#define KERNEL_TOTAL_INTERRUPTS 512

// 100MB heap size
#define KERNEL_HEAP_SIZE_BYTES 104857600
#define KERNEL_HEAP_BLOCK_SIZE 4096
#define KERNEL_HEAP_ADDRESS 0x01000000 
#define KERNEL_HEAP_TABLE_ADDRESS 0x00007E00

#define KERNEL_SECTOR_SIZE 512

#define KERNEL_MAX_FILESYSTEMS 12
#define KERNEL_MAX_FILE_DESCRIPTORS 512

#define KERNEL_MAX_PATH 108

#define KERNEL_TOTAL_GDT_SEGMENTS 6

#define KERNEL_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define KERNEL_USER_PROGRAM_STACK_SIZE 1024 * 16
#warning 这个栈地址很怪, 它是小于程序初始地址0x400000的
#define KERNEL_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define KERNEL_PROGRAM_VIRTUAL_STACK_ADDRESS_END KERNEL_PROGRAM_VIRTUAL_STACK_ADDRESS_START - KERNEL_USER_PROGRAM_STACK_SIZE

#define KERNEL_MAX_PROGRAM_ALLOCATIONS 1024
#define KERNEL_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define KERNEL_MAX_ISR80H_COMMANDS 1024

#define KERNEL_KEYBOARD_BUFFER_SIZE 1024

#endif